export const HOME_UNIVERSITY_LIST = Object.freeze([
  'Oxford University',
  'Stanford University',
  'Massachusetts Institute of Technology',
  'Harvard University',
  'Cambridge University',
  'Princeton University',
  'California Institute of Technology',
  'Imperial College London',
  'University of California, Berkeley',
  'Yale University',
  'Swiss Federal Institute of Technology',
  'Tsinghua University',
  'University of Chicago',
  'Peking University',
  'Johns Hopkins University',
]);

export const COUNTRY_LIST = Object.freeze([
  'Australia',
  'Bangladesh',
  'Brazil',
  'Canada',
  'China',
  'Ethiopia',
  'France',
  'Germany',
  'Ghana',
  'India',
  'Indonesia',
  'Japan',
  'Kazakhstan',
  'Malaysia',
  'Mexico',
  'Mongolia',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Pakistan',
  'Russia',
  'Spain',
  'Taiwan',
  'Thailand',
  'United Kingdom',
  'United States',
  'Uzbekistan',
  'Vietnam',
]);
