export const PATH = Object.freeze({
  root: '/',
  login: '/login',
  allBoard: '/board/all',
  internationalBoard: '/board/international',
  post: '/post/:postId',
  postCreation: '/post/create',
  search: '/search',
  myPage: '/mypage',
  myPost: '/mypage/my-post',
  bookmark: '/mypage/bookmark',
  findId: '/account/find-id',
  findPw: '/account/find-pw',
  signUp: '/account/signup',
});
